twitter_etl:
  target: dev
  outputs:
    dev:
      type: postgres
      host: twitter_etl_postgres
      user: twitter
      password: twitterpass
      dbname: twitter_etl
      schema: public
      port: 5432
